--------------------------------------------------------
-- Archivo creado  - sábado-marzo-28-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "TAW23"."COMMENTS" 
   (	"ID" NUMBER(9,0), 
	"USER_ID" NUMBER(9,0), 
	"POST_ID" NUMBER(9,0), 
	"CONTENT" VARCHAR2(1500 BYTE), 
	"DATETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table FRIENDS
--------------------------------------------------------

  CREATE TABLE "TAW23"."FRIENDS" 
   (	"USER_ID" NUMBER(9,0), 
	"FRIEND_ID" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table GROUPS
--------------------------------------------------------

  CREATE TABLE "TAW23"."GROUPS" 
   (	"ID" NUMBER(9,0), 
	"ADMIN" NUMBER(9,0), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "TAW23"."POST" 
   (	"ID" NUMBER(9,0), 
	"USER_ID" NUMBER(9,0), 
	"GROUP_ID" NUMBER(9,0), 
	"CONTENT" VARCHAR2(3000 BYTE), 
	"DATETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "TAW23"."USERS" 
   (	"ID" NUMBER(9,0), 
	"PASSWORD" VARCHAR2(32 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"TYPE" NUMBER(9,0), 
	"BLOCKED" NUMBER(9,0), 
	"NOTIFICATIONS" NUMBER(9,0), 
	"BIRTHDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
 

   COMMENT ON COLUMN "TAW23"."USERS"."TYPE" IS 'If 1 -> admin 
If 0 -> user';
 
   COMMENT ON COLUMN "TAW23"."USERS"."BLOCKED" IS 'If 1 -> can''t login 
If 0 -> can login';
 
   COMMENT ON COLUMN "TAW23"."USERS"."NOTIFICATIONS" IS 'If 1 -> have notifications 
If 0 -> don''t have';
--------------------------------------------------------
--  DDL for Table USERS_GROUP
--------------------------------------------------------

  CREATE TABLE "TAW23"."USERS_GROUP" 
   (	"USER_ID" NUMBER(9,0), 
	"GROUP_ID" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
REM INSERTING into TAW23.COMMENTS
SET DEFINE OFF;
Insert into TAW23.COMMENTS (ID,USER_ID,POST_ID,CONTENT,DATETIME) values ('65427','32758','23526','¡¡Seguro que durais mucho!!',to_date('22/03/15','DD/MM/RR'));
Insert into TAW23.COMMENTS (ID,USER_ID,POST_ID,CONTENT,DATETIME) values ('62535','32758','23526','Te lo dije, no era de fiar...',to_date('24/03/15','DD/MM/RR'));
Insert into TAW23.COMMENTS (ID,USER_ID,POST_ID,CONTENT,DATETIME) values ('63463','73824','23526',':(... A ver si nos vemos pavo... ánimo',to_date('24/03/15','DD/MM/RR'));
REM INSERTING into TAW23.FRIENDS
SET DEFINE OFF;
REM INSERTING into TAW23.GROUPS
SET DEFINE OFF;
Insert into TAW23.GROUPS (ID,ADMIN,NAME) values ('142364786','12345','Música clásica');
REM INSERTING into TAW23.POST
SET DEFINE OFF;
Insert into TAW23.POST (ID,USER_ID,GROUP_ID,CONTENT,DATETIME) values ('56374','12345',null,'Pensaba en ti pero me has roto el corazón',to_date('24/03/15','DD/MM/RR'));
Insert into TAW23.POST (ID,USER_ID,GROUP_ID,CONTENT,DATETIME) values ('23526','12345',null,'Te quiero!!! <3',to_date('22/03/15','DD/MM/RR'));
Insert into TAW23.POST (ID,USER_ID,GROUP_ID,CONTENT,DATETIME) values ('53463','73824',null,'PARTY ESTA NOCHE!!!',to_date('20/03/15','DD/MM/RR'));
REM INSERTING into TAW23.USERS
SET DEFINE OFF;
Insert into TAW23.USERS (ID,PASSWORD,EMAIL,NAME,LASTNAME,TYPE,BLOCKED,NOTIFICATIONS,BIRTHDAY) values ('32758','926e27eecdbc7a18858b3798ba99bddd','pepito@hotmail.com','Pepe','Rodriguez','0','0','2',to_date('15/03/90','DD/MM/RR'));
Insert into TAW23.USERS (ID,PASSWORD,EMAIL,NAME,LASTNAME,TYPE,BLOCKED,NOTIFICATIONS,BIRTHDAY) values ('12345','259823af837e251e560ca1158a4e77c7','pato@gmail.com','Lucas','Gutierrez','0','0','0',to_date('08/07/87','DD/MM/RR'));
Insert into TAW23.USERS (ID,PASSWORD,EMAIL,NAME,LASTNAME,TYPE,BLOCKED,NOTIFICATIONS,BIRTHDAY) values ('73824','b066df4b917ef4546991544b100a187e','loquita@yahoo.es','Lucía','Mazaperros','0','0','0',to_date('28/06/91','DD/MM/RR'));
Insert into TAW23.USERS (ID,PASSWORD,EMAIL,NAME,LASTNAME,TYPE,BLOCKED,NOTIFICATIONS,BIRTHDAY) values ('99999','21232f297a57a5a743894a0e4a801fc3','admin@social.es','Administrador','1','1','0','0',to_date('01/01/15','DD/MM/RR'));
REM INSERTING into TAW23.USERS_GROUP
SET DEFINE OFF;
Insert into TAW23.USERS_GROUP (USER_ID,GROUP_ID) values ('12345','142364786');
Insert into TAW23.USERS_GROUP (USER_ID,GROUP_ID) values ('32758','142364786');
--------------------------------------------------------
--  DDL for Index FRIENDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAW23"."FRIENDS_PK" ON "TAW23"."FRIENDS" ("USER_ID", "FRIEND_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAW23"."COMMENTS_PK" ON "TAW23"."COMMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAW23"."USERS_PK" ON "TAW23"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAW23"."POST_PK" ON "TAW23"."POST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index GROUPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAW23"."GROUPS_PK" ON "TAW23"."GROUPS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index USERS_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAW23"."USERS_GROUP_PK" ON "TAW23"."USERS_GROUP" ("USER_ID", "GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  Constraints for Table USERS_GROUP
--------------------------------------------------------

  ALTER TABLE "TAW23"."USERS_GROUP" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS_GROUP" MODIFY ("GROUP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS_GROUP" ADD CONSTRAINT "USERS_GROUP_PK" PRIMARY KEY ("USER_ID", "GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TAW23"."USERS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" MODIFY ("BLOCKED" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" MODIFY ("NOTIFICATIONS" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "TAW23"."FRIENDS" ADD CONSTRAINT "FRIENDS_PK" PRIMARY KEY ("USER_ID", "FRIEND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
 
  ALTER TABLE "TAW23"."FRIENDS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."FRIENDS" MODIFY ("FRIEND_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "TAW23"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
 
  ALTER TABLE "TAW23"."COMMENTS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."COMMENTS" MODIFY ("POST_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."COMMENTS" MODIFY ("DATETIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "TAW23"."POST" ADD CONSTRAINT "POST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
 
  ALTER TABLE "TAW23"."POST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."POST" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."POST" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."POST" MODIFY ("DATETIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUPS
--------------------------------------------------------

  ALTER TABLE "TAW23"."GROUPS" ADD CONSTRAINT "GROUPS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
 
  ALTER TABLE "TAW23"."GROUPS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."GROUPS" MODIFY ("ADMIN" NOT NULL ENABLE);
 
  ALTER TABLE "TAW23"."GROUPS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "TAW23"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK1" FOREIGN KEY ("POST_ID")
	  REFERENCES "TAW23"."POST" ("ID") ENABLE;
 
  ALTER TABLE "TAW23"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "TAW23"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "TAW23"."FRIENDS" ADD CONSTRAINT "FRIENDS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "TAW23"."USERS" ("ID") ENABLE;
 
  ALTER TABLE "TAW23"."FRIENDS" ADD CONSTRAINT "FRIENDS_FK2" FOREIGN KEY ("FRIEND_ID")
	  REFERENCES "TAW23"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUPS
--------------------------------------------------------

  ALTER TABLE "TAW23"."GROUPS" ADD CONSTRAINT "GROUPS_FK1" FOREIGN KEY ("ADMIN")
	  REFERENCES "TAW23"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "TAW23"."POST" ADD CONSTRAINT "POST_FK1" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "TAW23"."GROUPS" ("ID") ENABLE;
 
  ALTER TABLE "TAW23"."POST" ADD CONSTRAINT "POST_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "TAW23"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS_GROUP
--------------------------------------------------------

  ALTER TABLE "TAW23"."USERS_GROUP" ADD CONSTRAINT "USERS_GROUP_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "TAW23"."USERS" ("ID") ENABLE;
 
  ALTER TABLE "TAW23"."USERS_GROUP" ADD CONSTRAINT "USERS_GROUP_FK2" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "TAW23"."GROUPS" ("ID") ENABLE;
